### ISSUE TITLE
Add David Dotson as team member

### ISSUE THREAD

**Issue by kain88-de** [conda-forge/datreant.core-feedstock#2]
@conda-forge/core Could you please add @dotsdl to the team for this repository

**Comment by jakirkham** [comment]
So this hasn't happened yet only because our team update script is having issues. There is a proposed fix in the pipeline that merely needs a review and merge.

xref: https://github.com/conda-forge/conda-forge.github.io/pull/280

**Comment by jakirkham** [comment]
In this case, it is a matter of @dotsdl accepting the email invite to join conda-forge. Have you asked him about it?

**Comment by dotsdl** [comment]
I think it went through? Sorry about the delay...the email was rotting in my spam folder.

**Comment by jakirkham** [comment]
No worries. Am well versed with how things can get buried. Glad you got it sorted. Will close this out.
